[package]
name = "kadent"
version = "0.1.0"
edition = "2024"

[profile.profiling]
inherits = "release"
debug = true

[dependencies]
dirs = "6.0.0"
eframe = "0.34.3"
egui_extras = { version = "0.34.3", features = ["all_loaders", "syntect"] }
hound = "3.5.1"
kasl = { version = "0.2.35", features = ["cranelift"] }
midir = "0.11.0"
rfd = "0.17.2"
ringbuf = "0.5.0"
serde_json = "1.0.150"
cpal = "0.18.1"
syntect = "5.3.0"
uuid = { version = "1.24.1", features = ["v4"] }
sode = "0.1.0"
rayon = "1.12.0"
rand = "0.10.2"

[build-dependencies]
syntect = "5.3.0"

[package.metadata.bundle]
name = "Kadent"
identifier = "com.hatya.kadent"
version = "0.1.0"
category = "Music"
copyright = "© 2026 Shuntaro Kasatani"
osx_info_plist_exts = ["info_ext.plist"]
